language: swift
osx_image: xcode11.6
notifications:
  slack: eskaria:RRTsJOW40z95SajyTLBy7lxy
script:
  - swift package generate-xcodeproj
  - xcodebuild build -sdk iphoneos -scheme 'EKIPLocation-Package'
